### ISSUE TITLE
How to split train/test？

### ISSUE THREAD

**Issue by xiaomingjie** [jackd/shapenet#3]
Hi @jackd again..
I just generated point cloud but it seems that one category one hdf5 file. So unlike those one model one file dataset, how can I split train/test data？
Thanks..

**Comment by jackd** [comment]
As far as I'm aware, there's no official test/train split promoted by the dataset providers. If you really want two separate files you can modify the `path` property of `PointCloudAutoSavingManager`, but I think you'd be better off just using `dids.Dataset.subset` on the entire dataset. This way you can dynamically change test/train split without needing to rewrite the files, and you can do the same thing for multiple dataset. I've added an [example](https://github.com/jackd/shapenet/blob/master/example/core/train_test_split.py).

**Comment by xiaomingjie** [comment]
Actually, there is an official train/test split file .csv on ShapeNet website..[here](http://shapenet.cs.stanford.edu/shapenet/obj-zip/SHREC16/all.csv)
It looks like the form below

id | synsetId | subSynsetId | modelId | split
1119 | 2691156 | 2690373 | 50da48c8e7644508fca1f1143bb6bc17 | test

According to this .csv file, one line is one single item in  one certain category. I think this file is more convenient because maybe users would use other data such as RGB images or depth images as well. And this file will help to organize all the data..
So I wonder if the sample point cloud could be one file per model instead of one file per category?

**Comment by jackd** [comment]
Thanks for the link to the official split. I've added a `get_test_train_split` to [`shapenet.core`](https://github.com/jackd/shapenet/blob/master/core/__init__.py). I've also updated the [example](https://github.com/jackd/shapenet/blob/master/example/core/train_test_split.py) to use this official split. Note you can take exactly the same approach as in the example (using `dids.Dataset.subset`) regardless of the type of data (RGB, depth etc), so I won't be creating specific scripts for creating separate train/test/eval files for each dataset. Splitting on categories makes sense since it's quite common to target a model for a specific category, but (at least in research) it's very uncommon to only require access to the training dataset (and not testing), and not everyone uses the same split.

If you only need a subset of the data and don't want to store the rest (e.g. to evaluate a pretrained model), you can always mock something up specifying a limited set of `example_ids` based on the scripts provided.

**Comment by xiaomingjie** [comment]
I agree on "it's quite common to target a model for a specific category"
I mean when people put the training data into their network, they usually take several single items once (with batchsize=32 or blabla). So I think all 4000+model in one hdf5 file is not convenient because I have to load them all but only use 32 of them once. And rendering RGB imgs are also item by item instead of all items zipped in one file...
BTW, I am really appreciated that you help me a lot here.

**Comment by jackd** [comment]
I see the confusion. None of the datasets made available in this repository load all data into memory upon opening. They are designed to load the necessary data as you need it - so just because the hdf5 datasets contain 4000+ models doesn't mean they are all loaded. Similarly, opening a zip file with 4000+ files isn't the same as loading the contents of all 4000+. While this makes browsing them potentially more difficult with a standard file manager, it makes access much faster - particularly on spinning disk drives - compared to individual files. I attempt to resolve the access issue by implementing a common interface - `dids.Dataset`. It should be straight forward enough for anyone to write out the data to seperate files if they desire, but the exact format they use will vary from case-to-case, and I'd rather not have `n` different ways of achieving the same thing.

There's an argument for having a small number of slightly smaller files - particularly for distributed training - but I don't do any of that, so I'll leave that for pull requests/branches. Similarly, having a separate train/test/eval file has its merits - but also problems/complications. I would like to keep this repository as clean and simple as feasibly possible.

**Comment by xiaomingjie** [comment]
I get it. Still thank you very much for helping me a lot!
I find another amazing job of yours, the ffd, and I am going to look into it. It seems that what you have done is exactly what I want, I mean the dataset.
Thanks again!

**Comment by jackd** [comment]
Closing this issue, but feel free to keep submitting issues for things that are wrong/unclear. My workload varies so I can't always get onto them ASAP, but I'll get there eventually...

**Comment by SaShukla090** [comment]
> Actually, there is an official train/test split file .csv on ShapeNet website..[here](http://shapenet.cs.stanford.edu/shapenet/obj-zip/SHREC16/all.csv) It looks like the form below
> 
> id | synsetId | subSynsetId | modelId | split 1119 | 2691156 | 2690373 | 50da48c8e7644508fca1f1143bb6bc17 | test
> 
> According to this .csv file, one line is one single item in one certain category. I think this file is more convenient because maybe users would use other data such as RGB images or depth images as well. And this file will help to organize all the data.. So I wonder if the sample point cloud could be one file per model instead of one file per category?

link not working, can directly share the csv file
