### ISSUE TITLE
Using render_cat.py to render car is slow.

### ISSUE THREAD

**Issue by luotuoqingshan** [jackd/shapenet#8]
I run `python render_cat.py car -n 1` but it is slow.
I render some other categories like plane, sofa, bench and it is done very fast.
When I turn to car, it has taken more than one day but only half of them are rendered.
Although car has many examples, table also has many and it is done very fast.

**Comment by jackd** [comment]
You're absolutely right. My background isn't in computer graphics, but my understanding is as follows: cars usually have more smooth surfaces than tables. Triangular meshes simulate smooth surfaces by having a large number of small triangles, and meshes with a large number of triangles take longer to render.

On a different note, I've never found that car renderings particularly satisfying - lighting never looks very good - but I also don't want to have to explain in papers why I made a special case for cars since that just looks like dodgy hacks. Feel free to hack the script yourself though, and if you find anything that radically speeds things up without affecting quality I'm happy to accept pull requests.
